language: node_js
node_js:
- '11'
install:
- npm install
- npm install pm2
- sh ./tools/bgcinfra/configs/deploy.sh
script:
- node_modules/.bin/pm2 deploy ./tools/bgcinfra/configs/ecosystem.config.js development
env:
- CI=false
before_deploy:
- cd ..
before_install:
- mkdir -p ~/.ssh
- openssl aes-256-cbc -K $encrypted_3f4d3615b6b0_key -iv $encrypted_3f4d3615b6b0_iv
  -in BGCDev.pem.enc -out ~\/.ssh/BGCDev.pem -d
