language: node_js
node_js:
- '11'

branches:
  only:
    - master
    - develop


before_install:
- openssl aes-256-cbc -K $encrypted_3f4d3615b6b0_key -iv $encrypted_3f4d3615b6b0_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar

install:
- npm install -g pm2

script:
- bash ./tools/bgcinfra/configs/deploy.sh

env:
- CI=false

