language: node_js
node_js:
- '11'

branches:
  only:
    - master
    - develop


before_install:
- openssl aes-256-cbc -K $encrypted_3f4d3615b6b0_key -iv $encrypted_3f4d3615b6b0_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- cp ./BGCDev.pem ~/.ssh/BGCDev.pem
- cp ./BGCProd.pem ~/.ssh/BGCProd.pem

install:
- npm install -g pm2

script:
- ls -al $TRAVIS_BUILD_DIR
- bash ./tools/bgcinfra/configs/deploy.sh
- ls -al ~/.ssh

env:
- CI=false

