version: 0.1
phases:
  install:
    commands:
      - npm install

  pre_build:
    commands:
      - npm test

  post_build:
    commands:
      - cd ./api && ../node_modules/.bin/sequelize db:migrate

artifacts:
  type: zip