steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'ubuntu'
  args: ['ls', '-al']
- name: 'ubuntu'
  args: ['./node_modules/.bin/sequelize', 'db:migrate']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']