AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: GET

  GetGameFunction:
      Type: AWS::Serverless::Function
      Properties:
        Handler: getGame.handler
        Runtime: nodejs6.10
        CodeUri: ./
        Events:
          GetGameAPI:
            Type: Api
            Properties:
              Path: /game/{gameid}
              Method: GET
        Policies: AWSLambdaDynamoDBExecutionRole