AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Boardgame Week-end backend
Resources:
  GetGameFunction:
      Type: AWS::Serverless::Function
      Properties:
        Handler: getGame.handler
        Runtime: nodejs6.10
        CodeUri: ./api
        Events:
          GetGameAPI:
            Type: Api
            Properties:
              Path: /game/{gameid}
              Method: GET
        Policies: AmazonDynamoDBReadOnlyAccess

  SearchGameFunction:
        Type: AWS::Serverless::Function
        Properties:
          Handler: searchGame.handler
          Runtime: nodejs6.10
          CodeUri: ./api
          Events:
            GetGameAPI:
              Type: Api
              Properties:
                Path: /game/_search/{name}
                Method: GET
