version: '3'
services:
  db:
    container_name: "bgwe_backend_testdb_1"
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: Bgwe1234
      POSTGRES_DB: bgwe_test
    ports:
      - "5433:5432"

  apiserver:
    container_name: "bgwe_backend_testapiserver_1"
    depends_on:
      - "db"
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    restart: always
    environment:
      PORT: 3001
      JWT_SECRET_KEY: "bgwe1234"
      DB_HOSTNAME: "bgwe_backend_testdb_1"
      DB_NAME: bgwe_test
      DB_PASSWORD: Bgwe1234
      DB_USERNAME: dbadmin
      NODE_ENV: testing
    expose:
      - "3001"
    ports:
      - "3001:3001"
    volumes:
      - ../../:/home/node/app
    command:  >
      bash -c "yarn install
      && sleep 15
      && cd api/
      && ../node_modules/.bin/sequelize db:migrate
      && cd ..
      && yarn start"
