DB_USER: dbadmin
DB_PASSWORD: Bgwe1234
DB_NAME: bgwe_test
CONTAINER_DB_HOST_PORT: 7654
JWT_SECRET: bgwe1234
CONTAINER_DB_NAME: bgwe_backend_testdb_1
CONTAINER_APISERVER_NAME: bgwe_backend_testapiserver_1
APISERVER_ENV: testing
CONTAINER_APISERVER_HOST_PORT: 4000
CONTAINER_APPMETRICS_HOST_PORT: 4001
CONTAINER_APISERVER_SRC_DIR: /Users/fservais/Projects/BoardgameWE/
TEST_HOST: localhost
TEST_PORT: 3000
TEST_PROTOCOL: http
