version: '3'
services:
  db:
    container_name: "bgwe_backend_db_1"
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: Bgwe1234
      POSTGRES_DB: bgwe_dev
    expose:
      - "5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
  apiserver:
    container_name: "bgwe_backend_apiserver_1"
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    restart: always
    environment:
      PORT: 3000
      JWT_SECRET_KEY: "bgwe1234"
      DB_HOSTNAME: "bgwe_backend_db_1"
      DB_NAME: bgwe_dev
      DB_PASSWORD: Bgwe1234
      DB_USERNAME: dbadmin
      NODE_ENV: development
    expose: 
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ../:/home/node/app
    command:  >
      bash -c "npm install 
      && cd api/ 
      && ../node_modules/.bin/sequelize db:migrate
      && cd ..
      && npm start"
