version: '3'
services:
  db:
    container_name: "bgwe_backend_db_1"
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: POSTGRES_DB
    expose:
      - "5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  apiserver:
    container_name: "bgwe_backend_apiserver_1"
    depends_on:
      - "db"
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    restart: always
    environment:
      PORT: 3000
      NODE_ENV: development
      JWT_SECRET_KEY: JWT_SECRET_KEY
      DB_HOSTNAME: DB_HOSTNAME
      DB_NAME: DB_NAME
      DB_PASSWORD: DB_PASSWORD
      DB_USERNAME: DB_USERNAME
      SENDGRID_API_KEY: SENDGRID_API_KEY
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ../:/home/node/app
    command:  >
      bash -c "npm install
      && ./node_modules/apidoc/bin/apidoc -i api/ -o doc/
      && sleep 15
      && cd api/
      && ../node_modules/.bin/sequelize db:migrate
      && cd ..
      && npm start"
