services:
  apiserver:
    command: bash -c "yarn install && sleep 15 && cd api/ && ../node_modules/.bin/sequelize
      db:migrate && cd .. && yarn start"
    container_name: bgwe_backend_testapiserver_1
    depends_on:
    - db
    environment:
      DB_HOSTNAME: bgwe_backend_testdb_1
      DB_NAME: bgwe_test
      DB_PASSWORD: Bgwe1234
      DB_USERNAME: dbadmin
      JWT_SECRET_KEY: bgwe1234
      NODE_ENV: testing
      PORT: 3000
      TEST_HOST: localhost
      TEST_PORT: '3000'
      TEST_PROTOCOL: http
    image: node:8
    ports:
    - 4000:3000
    restart: always
    user: node
    volumes:
    - /Users/fservais/Projects/BoardgameWE/:/home/node/app
    working_dir: /home/node/app
  db:
    container_name: bgwe_backend_testdb_1
    environment:
      POSTGRES_DB: bgwe_test
      POSTGRES_PASSWORD: Bgwe1234
      POSTGRES_USER: dbadmin
    image: postgres:9.6
    ports:
    - 7654:5432
    restart: always
version: '3'
