name: CI

on:
  push:
    branches:
    - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: npm install
      run: npm install
    - name: Install dependencies
      run: npm install pm2
    - name: Deploy key
      run: sh ./tools/bgcinfra/configs/deploy.sh
      env:
        SSH_KEY: ${{ secrets.DEV_ENV_SSH_KEY }}
    - name: Stash changes
      run: git stash
    - name: Deploy
      run: node_modules/.bin/pm2 deploy ./tools/bgcinfra/configs/ecosystem.config.js development
