name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: npm install
      run: npm install
    - name: Install dependencies
      run: npm install -g pm2
    - name: Add SSH Key
      run: echo ${{ secrets.SSH_KEY }} | ssh-add -
    - name: Deploy
      run: pm2 deploy ./tools/bgcinfra/configs/ecosystem.config.js production
